import FotTUC from './1.png';
import logo from './tuc.png';
import lanyardpurple from './lanyardungu.png';
import lanyardred from './lanyardred.png';
import audition from './tucaudition.png';
import shirt from './t-shirtred.png';
import TUCFAM from './tucfamily.png';
import tumbler from './tumbler.png';
import unceasingpraise from './unceasingpraise.png';
import discover from './discover.png';

export {FotTUC};
export {logo};
export {lanyardpurple};
export {lanyardred};
export {audition};
export {shirt};
export {TUCFAM};
export {tumbler};
export {unceasingpraise};
export {discover};